[project]
name = "python-repo-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
authors = [{ name = "Your Name", email = "j.vargas.g.d@gmail.com" }]
license = { file = "LICENSE" }

[dependency-groups]
dev = [
    "ruff>=0.13.2",
]
